apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
  - name: pytorch
    image: pytorch/pytorch:latest
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 1; done;"]
    resources:
      limits:
        nvidia.com/gpu: 1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /workspace
      name: my-hostpath
  volumes:
  - name: my-hostpath
    hostPath:
      path: /home/mrt/Projects/Kubernetes
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: minerva
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
spec:
  containers:
  - name: pytorch
    image: pytorch/pytorch:latest
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 1; done;"]
    resources:
      limits:
        nvidia.com/gpu: 1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /workspace
      name: my-hostpath
  volumes:
  - name: my-hostpath
    hostPath:
      path: /home/mrt/Projects/Kubernetes
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: tetis
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
