apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch
  labels:
    app: pytorch
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
      - name: pytorch
        image: pytorch/pytorch:latest

        # This runs a bash shell, but it finishes as soon as it starts
        # command: ["bash"]
        
        # This is a trick to keep the pod up and running
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 10; done;"]

        # This runs a python file
        # command: ["python", "/workspace/main.py"]

        # This makes sure that we can write to the mounted volume
        # command: ["/bin/touch", "/workspace/escrito_desde_el_pod"]

        resources:
          limits:
            nvidia.com/gpu: 2
        volumeMounts:
        - mountPath: /workspace
          name: data
      volumes:
      - name: data
        hostPath:
          path: /workspace
          type: Directory
