apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch
  labels:
    app: pytorch
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
      - name: pytorch
        image: pytorch/pytorch:latest
        # command: ["bash"]
        # The containers exit as soon as they finish their command, this is a trick to keep them up and running
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 10; done;"]
        resources:
          limits:
            nvidia.com/gpu: 2