#!/bin/bash

kubectl apply -f local_storage.yaml --namespace jupyterhub

helm upgrade --cleanup-on-fail --install jupyterhub jupyterhub/jupyterhub --namespace jupyterhub --create-namespace --values config.yaml

sleep 20s

kubectl port-forward service/proxy-public 8080:http --namespace jupyterhub
